name: CD

on:
  push:
    tags:
      - '*'

jobs:
  pypi-build:
    name: Build package for PyPI
    if: github.repository == 'access-nri/model-config-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build dependencies
        run: python3 -m pip install --upgrade build

      - name: Build distributions
        run: python3 -m build

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist

  pypi-publish:
    # Split build and publish to restrict trusted publishing to just this workflow
    needs: ['pypi-build']
    name: Publish to PyPI.org
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
