name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pypi-build:
    name: Build package for PyPI
    if: github.repository == 'access-nri/model-config-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install build dependencies
        run: python3 -m pip install --upgrade build

      - name: Build distributions
        run: python3 -m build

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install model_config_tests
        run: pip install -e '.[test]'

      - name: Run tests
        run: pytest -s tests
