name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install model_config_tests
        run: pip install -e '.[test]'

      - name: Run tests
        run: pytest -s tests
