name: Scheduled Checks
on:
  workflow_call:
  # Workflows that call this workflow use the following triggers:
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'  # once a month
jobs:
  setup:
    name: Setup Tasks
    runs-on: ubuntu-latest
    outputs:
      refs: ${{ steps.get-scheduled-tests.outputs.refs }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Get all tag/branches of configs for scheduled tests
        id: get-scheduled-tests
        run: |
          # Pattern to exclude refs that include ? or * or [
          exclude_pattern="[\\*\\?\\[]"

          # Filter out keys under scheduled that are not default and do not
          # include some regex characters
          refs=$(jq --compact-output --raw-output --arg pattern "$exclude_pattern" '
            .scheduled | del(.default) | keys | map(select(test($pattern) | not))
          ' config/ci.json)

          echo "refs=$refs" >> $GITHUB_OUTPUT

  repro-ci:
    # We use this reusable workflow with a matrix strategy rather than calling repro-ci.yml, as
    # we may want to do config-branch-specific tasks after the matrixed repro-ci.yml has completed.
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        config-ref: ${{ fromJson(needs.setup.outputs.refs) }}
    uses: ./.github/workflows/config-schedule-2-start.yml
    with:
      config-ref: ${{ matrix.config-ref }}
    secrets: inherit
    permissions:
      checks: write
      contents: write
      issues: write
